[pytest]
# 参数
addopts = -s --html=report/report.html --reruns 3
# 搜索哪个文件夹
testpaths = ./
# 搜索的文件夹以test_开头
python_files = test_*.py
# 搜索的类名以Test开头
python_classes = Test*
# 搜索 的方法名以test_开头
python_functions = test_*

