[pytest]
addopts = -v -s --alluredir=./allure-results
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: smoke test cases
    positive: positive test cases
    negative: negative test cases
    boundary: boundary test cases
    critical: critical priority test cases
    normal: normal priority test cases
    minor: minor priority test cases
    tax_declare: tax declare related test cases
    expense_config: expense config related test cases
    predict_config: predict config related test cases